/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:803ed8ea-7a5a-4b80-a073-cb9d7d192824",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nJxZKrSuW",
    "aws_user_pools_web_client_id": "64orfcclt4fpgvefrgi91desdh",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "diall3f29946034eb4a6493e0bc724085a09663201-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
